In [9]:
data = pd.read_csv("../Data/XXHq_2013.csv")
weighted =  pd.read_csv("../Data/weighted_2013.csv")

In [27]:
weighted['q1'].value_counts()

6.0    3473
5.0    3203
4.0    3098
7.0    2320
3.0    1368
1.0      26
2.0      18
Name: q1, dtype: int64

In [29]:
#[print(col) for col in weighted.columns]
weighted.describe()

,raceeth,record,orig_rec,q1,q2,q3,q4,q6,q7,qn8,qn9,qn10,qn11,qn12,qn13,...,qnsoda2,qnsoda3,qnmilk0,qnmilk1,qnmilk2,qnnobkft,qndlype,qnpa0day,qnpa7day,BMIPCT,qnowt,qnobese,weight,stratum,psu
count,13265.000000,13583.000000,0.0,13506.000000,13571.000000,13504.000000,13352.000000,12579.000000,12579.000000,8723.000000,13559.000000,13545.000000,7858.000000,8019.000000,13252.000000,...,13324.000000,13324.000000,13280.000000,13280.000000,13280.000000,13323.000000,13228.000000,13310.000000,13310.000000,1.257900e+04,12579.000000,12579.000000,13583.000000,13583.000000,13583.000000
mean,4.926197,6817.022086,NaN,5.157041,1.512121,2.501999,1.743559,1.691241,67.906503,1.118423,1.922413,1.772905,1.903156,1.597581,1.829460,...,1.805764,1.880216,1.787801,1.617395,1.757154,1.854012,1.698292,1.836814,1.727874,6.350569e+01,1.835917,1.858017,1.000002,153.977325,219787.545535
std,1.574850,3935.946763,NaN,1.263737,0.499871,1.148267,0.436684,0.104697,16.898213,0.323126,0.267530,0.418970,0.295764,0.490416,0.376121,...,0.395626,0.324721,0.408880,0.486041,0.428819,0.353108,0.459017,0.369549,0.445071,2.856532e+01,0.370366,0.349046,0.878130,50.994929,151316.769849
min,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.270000,29.940000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.335760e-10,1.000000,1.000000,0.028600,101.000000,10970.000000
25%,3.000000,3406.500000,NaN,4.000000,1.000000,1.000000,1.000000,1.600000,56.250000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,...,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,4.253226e+01,2.000000,2.000000,0.447000,103.000000,60890.000000
50%,5.000000,6818.000000,NaN,5.000000,2.000000,3.000000,2.000000,1.680000,64.410000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,6.915981e+01,2.000000,2.000000,0.792700,113.000000,181470.000000
75%,6.000000,10228.500000,NaN,6.000000,2.000000,4.000000,2.000000,1.780000,76.200000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,8.895752e+01,2.000000,2.000000,1.222200,211.000000,290770.000000
max,8.000000,13633.000000,NaN,7.000000,2.000000,5.000000,2.000000,2.110000,180.990000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,9.994894e+01,2.000000,2.000000,9.234900,214.000000,530330.000000

In [33]:
weighted.head()
weighted.drop(columns=['site','record','orig_rec'], inplace=True)

In [ ]:


data.describe()
data.hist(bins=50, figsize=(20,15))
data.value_counts()

missingRows = pd.isnull(data).sum(axis=1) > 0
missingCols = pd.isnull(data).sum(axis=0) > 0